### PR TITLE
fix: refactor custom partition mapping config

### LINKED ISSUE #16: BUG: Remap partition number from destination cluster to source cluster when booting up to reset offset
https://github.com/zerodha/kaf-relay/blob/main/producer.go#L48
^ We allow mapping from partition X from source to partition Y to destination. We should remap this when we are pulling destination offsets for resetting consumer offsets.

### PR DESCRIPTION
**Pull request by kalbhor**
This MR attempts to fix #16

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -97,8 +97,8 @@ type ProducerCfg struct {
 	FlushBatchSize int `koanf:"flush_batch_size"`
 	// compression
 	Compression string `koanf:"compression"` // gzip/snappy/lz4/zstd/none
-	// custom partition for topics
-	TopicsPartition map[string]int32 `koanf:"partitioning"`
+	// custom partition for topics. eg: topic -> [[src_partition_1, dest_partition_1], [src_partition_2, dest_partition_2]]
+	TopicsPartition map[string][][]int32 `koanf:"partitioning"`
```
Comment (joeirimpan) [inline config.go]: can koanf load it as map[string][]topicPartition?

```golang
type topicPartition struct {
    src int32
    dest int32
}
```

**Review by joeirimpan — CHANGES_REQUESTED** [review]
